os_ti/urls.py
from django.urls import path
from . import views
 
app_name='os_ti'
urlpatterns = [
    path('os/reset/conclusao/123654/', views.mudadados, name='mudados'),
    path('os/alterar_equipes/123456/', views.alterar_equipes, name='alterar_equipes'),

    path('', views.os_index, name='os_index'),
    path('finalizados/', views.os_finalizados, name='os_finalizados'),
    path('painel/', views.os_painel, name='os_painel'),
    path('os/', views.add_os, name='add_os'),
    path('os/contar-os/', views.contagem_os, name='contagem_os'),
    path('os/salvar-contagem/', views.salvar_contagem_os, name='salvar_contagem_os'),

    path('os/painel/<id>/', views.detalhes_os, name='detalhes_os'),
    path('os/painel/<id>/pontos', views.pontos_os, name='pontos_os'),
    path('imprimir/', views.os_index, name='imprimir_nada'),
    path('imprimir/<ids>/', views.imprimir_varias_os, name='imprimir_varias'),
    path('os/painel/<id>/imprimir/', views.imprimir_os, name='imprimir'),
    path('os/painel/<id>/alterar_status/<opcao>', views.change_status_os, name='change_status_os'),
    path('os/<int:id>/alterar_prioridade/<int:opcao>', views.change_prioridade_os, name='change_prioridade_os'),
    path('os/painel/<id>/atender', views.atender_os, name='atender_os'),

    path('os/kpi', views.graficos, name='kpi'),
    path('os/kpi/ver-mais/<tipo>/<subtipo>/', views.graficos_ver_mais, name='kpi_ver_mais'),
    path('funcionario', views.funcionarios_listar, name='funcionarios'),
    path('funcionario/cadastrar/', views.funcionario_cadastrar, name='cadastrar funcionario'),
    path('funcionario/editar/<id>/', views.funcionario_editar, name='editar funcionario'),
    path('funcionario/deletar/<id>/', views.funcionario_deletar, name='deletar funcionario'),

    path('os/painel/<id>/equipe/', views.atribuir_equipe, name='atribuir equipe'),
    
    #acrescentados
    path('login/', views.loginPage, name='loginPage'),
    path('sairFunc/', views.sairFunc, name='sairFunc'),
    path('cadastroPessoa/', views.cadastroPessoa, name='cadastroPessoa'),
]

projeto_os_ti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('os_ti.urls')),
]

os_ti/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import OrdemDeServico, Funcionario_OS, OS_ext, OS_Linha_Tempo, Pessoa
from django.contrib.auth.models import Group
from django.forms import ModelChoiceField

class OS_Form(ModelForm):    
    
    class Meta:
        model = OrdemDeServico
        widgets = {
            'tipo': forms.Select(attrs={'readonly': True}),
            'secretaria': forms.Select(),
        }
        exclude = ['numero', 'dt_inclusao', 'dt_alteracao','dt_execucao', 'observacao_pontos','atendente', 'dt_conclusao', 'prioridade', 'status', 'contribuinte', 'pontos_atendidos', 'cadastrado_por', 'message_status', 'finalizado_por']


class OS_Form_Ponto(ModelForm):    
        
    class Meta:
        model = OrdemDeServico       
        widgets={
         'dt_execucao': forms.DateInput(attrs={'class': 'form-control', 'type':'date'}),
         }
        fields = ['pontos_atendidos', 'observacao_pontos', 'dt_execucao']

class PessoaChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.nome
    
class Funcionario_Form(ModelForm):

    pessoa = PessoaChoiceField(queryset=Pessoa.objects.none(), label='Selecione uma pessoa')

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None) or Group.objects.get(name='os_funcionario')
        super().__init__(*args, **kwargs)
        if grupo:
            self.fields['pessoa'].queryset = Pessoa.objects.filter(user__groups=grupo)

    class Meta:
        model = Funcionario_OS
        widgets = {'tipo_os': forms.HiddenInput()}
        fields = ['pessoa', 'nivel', 'tipo_os']

class Funcionario_Form_editar(ModelForm):

    pessoa = PessoaChoiceField(queryset=Pessoa.objects.none(), label='Selecione uma pessoa')

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None) or Group.objects.get(name='os_funcionario')
        super().__init__(*args, **kwargs)
        if grupo:
            self.fields['pessoa'].queryset = Pessoa.objects.filter(user__groups=grupo)

    class Meta:
        model = Funcionario_OS
        widgets = {'tipo_os': forms.HiddenInput()}
        fields = ['pessoa', 'nivel', 'tipo_os']


class Equipe_Form(ModelForm):
    class Meta:
        model = OS_ext
        widgets = {
            'equipe': forms.CheckboxSelectMultiple(),
            'os': forms.HiddenInput()

        }        
        exclude=[]

class NovaMensagemForm(forms.ModelForm):
    class Meta:
        model = OS_Linha_Tempo
        fields = ['os', 'pessoa', 'mensagem', 'anexo']
        widgets = {
            'os': forms.HiddenInput(),
            'pessoa': forms.HiddenInput(),
            'mensagem': forms.Textarea(attrs={'class': 'form-control h-100', 'rows': 6}),
            'anexo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }
        
#acrescentado
class CadastroForm(ModelForm):
    class Meta:
        model = Pessoa
        widgets = {
            'dt_nascimento':forms.TextInput(attrs={'type':'date'}),
            'cpf':forms.TextInput(attrs={'onkeydown': 'mascara(this, icpf)','onblur':'checkCPF(this.value)'}),
            'cep':forms.TextInput(attrs={'onkeydown': 'icep(this)','onblur':'getCEP(this)'}),
            'telefone':forms.TextInput(attrs={'onkeydown':'mascara(this, itel)'}),
        }
        fields=['matricula', 'secretaria', 'nome', 'email', 'telefone', 'dt_nascimento']
        exclude = ['user']

    # def clean_cpf(self):
    #     cpf = validate_cpf(self.cleaned_data["cpf"])
    #     return cpf

    def clean_telefone(self):
        telefone = self.cleaned_data["telefone"]
        telefone = telefone.replace('(', '')
        telefone = telefone.replace(' ', '')
        telefone = telefone.replace(')', '')
        telefone = telefone.replace('-', '')
        return telefone

os_ti/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import Pessoa
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.apps import apps
from .models import *
from projeto_os_ti.decorators import group_required
from django.contrib.auth.models import Group
from datetime import datetime
from django.db.models import Case, When, Count, Sum, IntegerField

from django.http import HttpResponse
from openpyxl import Workbook
from datetime import datetime, timedelta
from django.utils import timezone
from .custom import month_translate

#acrescentados
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

STATUS_CHOICES=(
        ('0','Novo'),
        ('1','Aguardando'),
        ('2','Em execução'),
        ('f','Finalizado')
    )
PRIORIDADE_CHOICES=(
        ('0','Normal'),
        ('1','Moderada'),
        ('2','Urgente'),
    )

@group_required('os_acesso')
def index(request):
    return render(request, 'os_index.html')

from django.db import connection

@login_required
def os_painel(request):    
    # meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    # bairros = OrdemDeServico.objects.values_list('bairro', flat=True).distinct()
    # data = []  

    # for bairro in bairros:
    #     total=OrdemDeServico.objects.filter(bairro=bairro, status__in=['0', '1', '2'], dt_solicitacao__year='2023').count()
    #     os_por_mes = OrdemDeServico.objects.filter(bairro=bairro, status__in=['0', '1', '2'], dt_solicitacao__year='2023').annotate(
    #         jan=Count('id', filter=models.Q(dt_solicitacao__month=1)),
    #         fev=Count('id', filter=models.Q(dt_solicitacao__month=2)),
    #         mar=Count('id', filter=models.Q(dt_solicitacao__month=3)),
    #         abr=Count('id', filter=models.Q(dt_solicitacao__month=4)),
    #         mai=Count('id', filter=models.Q(dt_solicitacao__month=5)),
    #         jun=Count('id', filter=models.Q(dt_solicitacao__month=6)),
    #         jul=Count('id', filter=models.Q(dt_solicitacao__month=7)),
    #         ago=Count('id', filter=models.Q(dt_solicitacao__month=8)),
    #         set=Count('id', filter=models.Q(dt_solicitacao__month=9)),
    #         out=Count('id', filter=models.Q(dt_solicitacao__month=10)),
    #         nov=Count('id', filter=models.Q(dt_solicitacao__month=11)),
    #         dez=Count('id', filter=models.Q(dt_solicitacao__month=12)),
    #     ).values('jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez')

    #     dt={'bairro': bairro, 'mes': os_por_mes, 'total': total}
    #     if not any(item['bairro'] == bairro for item in data):
    #         data.append(dt)
    # bairros = (
    #     OrdemDeServico.objects
    #     .filter(status__in=['0', '1', '2'], dt_solicitacao__year='2023')
    #     .values('bairro')
    #     .annotate(
    #         total=Count('id'),
    #         jan=Sum(models.Case(models.When(dt_solicitacao__month=1, then=1), default=0, output_field=models.IntegerField())),
    #         fev=Sum(models.Case(models.When(dt_solicitacao__month=2, then=1), default=0, output_field=models.IntegerField())),
    #         mar=Sum(models.Case(models.When(dt_solicitacao__month=3, then=1), default=0, output_field=models.IntegerField())),
    #         abr=Sum(models.Case(models.When(dt_solicitacao__month=4, then=1), default=0, output_field=models.IntegerField())),
    #         mai=Sum(models.Case(models.When(dt_solicitacao__month=5, then=1), default=0, output_field=models.IntegerField())),
    #         jun=Sum(models.Case(models.When(dt_solicitacao__month=6, then=1), default=0, output_field=models.IntegerField())),
    #         jul=Sum(models.Case(models.When(dt_solicitacao__month=7, then=1), default=0, output_field=models.IntegerField())),
    #         ago=Sum(models.Case(models.When(dt_solicitacao__month=8, then=1), default=0, output_field=models.IntegerField())),
    #         set=Sum(models.Case(models.When(dt_solicitacao__month=9, then=1), default=0, output_field=models.IntegerField())),
    #         out=Sum(models.Case(models.When(dt_solicitacao__month=10, then=1), default=0, output_field=models.IntegerField())),
    #         nov=Sum(models.Case(models.When(dt_solicitacao__month=11, then=1), default=0, output_field=models.IntegerField())),
    #         dez=Sum(models.Case(models.When(dt_solicitacao__month=12, then=1), default=0, output_field=models.IntegerField()))
    #     )
    # )

    # data = []
    # for bairro in bairros:
    #     bairro_data = {
    #         'bairro': bairro['bairro'],
    #         'mes': {
    #             'jan': bairro['jan'],
    #             'fev': bairro['fev'],
    #             'mar': bairro['mar'],
    #             'abr': bairro['abr'],
    #             'mai': bairro['mai'],
    #             'jun': bairro['jun'],
    #             'jul': bairro['jul'],
    #             'ago': bairro['ago'],
    #             'set': bairro['set'],
    #             'out': bairro['out'],
    #             'nov': bairro['nov'],
    #             'dez': bairro['dez'],
    #         },
    #         'total': bairro['total']
    #     }
    #     data.append(bairro_data)

    # query = '''
    # SELECT
    #     bairro,
    #     COUNT(*) AS total,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 1) AS `jan`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 2) AS `fev`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 3) AS `mar`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 4) AS `abr`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 5) AS `mai`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 6) AS `jun`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 7) AS `jul`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 8) AS `ago`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 9) AS `et`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 10) AS `out`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 11) AS `nov`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 12) AS `dez`
    # FROM
    #     os_ti_ordemdeservico
    # WHERE
    #     bairro IS NOT NULL
    #     AND status IN ('0', '1', '2')
    #     AND YEAR(dt_solicitacao) = 2023
    # GROUP BY
    #     bairro
    # '''

    # with connection.cursor() as cursor:
    #     cursor.execute(query)
    #     rows = cursor.fetchall()

    # data = []
    # for row in rows:
    #     bairro = row[0]
    #     total = row[1]
    #     meses = row[2:]
    #     os_por_mes = {meses[i]: value for i, value in enumerate(meses)}
    #     data.append({'bairro': bairro, 'mes': os_por_mes, 'total': total})

    # query = """
    #     SELECT (SELECT COUNT(*) FROM os_ti_ordemdeservico WHERE status!='f' and bairro = main.bairro GROUP BY bairro) as total, bairro, (SELECT COUNT(dt_solicitacao) FROM os_ti_ordemdeservico GROUP BY bairro), 
    #         CASE
    #             WHEN strftime('%m', dt_solicitacao) = '01' THEN 'Janeiro'
    #             WHEN strftime('%m', dt_solicitacao) = '02' THEN 'Fevereiro'
    #             WHEN strftime('%m', dt_solicitacao) = '03' THEN 'Março'
    #             WHEN strftime('%m', dt_solicitacao) = '04' THEN 'Abril'
    #             WHEN strftime('%m', dt_solicitacao) = '05' THEN 'Maio'
    #             WHEN strftime('%m', dt_solicitacao) = '06' THEN 'Junho'
    #             WHEN strftime('%m', dt_solicitacao) = '07' THEN 'Julho'
    #             WHEN strftime('%m', dt_solicitacao) = '08' THEN 'Agosto'
    #             WHEN strftime('%m', dt_solicitacao) = '09' THEN 'Setembro'
    #             WHEN strftime('%m', dt_solicitacao) = '10' THEN 'Outubro'
    #             WHEN strftime('%m', dt_solicitacao) = '11' THEN 'Novembro'
    #             WHEN strftime('%m', dt_solicitacao) = '12' THEN 'Dezembro'
    #             ELSE NULL
    #     END AS nome_mes
    #     FROM os_ti_ordemdeservico as main
    #     WHERE status != 'f'
    #     GROUP BY bairro
    #     ORDER BY bairro;
    #     """
    query = """
        SELECT (SELECT COUNT(*) FROM os_ti_ordemdeservico WHERE status!='f' and bairro = main.bairro GROUP BY bairro) as total,bairro, 
        COUNT(dt_solicitacao), 
        MONTHNAME(dt_solicitacao) AS nome_mes 
        FROM os_ti_ordemdeservico as main 
        WHERE status != 'f' 
        GROUP BY bairro, MONTH(dt_solicitacao) 
        ORDER BY bairro; 
    """
    with connection.cursor() as cursor:
        cursor.execute(query)
        results = cursor.fetchall()

    # print(results)
    resultados_formatados = []
    for row in results:
        total, bairro, count_dt_solicitacao, nome_mes = row
        resultado_dict = {
            'bairro': bairro,
            'total': total,
            'mes': nome_mes,
            'total_por_mes': count_dt_solicitacao
        }
        resultados_formatados.append(resultado_dict)

    bairros=[]
    for result in resultados_formatados:  
        bairros.append(result['bairro'])
    bairros_ = list(set(bairros))

    resultados_agrupados = []
    for b in bairros_:
        resultados_agrupados.append(
            {'bairro': b}
        )

    for result in resultados_formatados:
        bairro = result['bairro']
        mes = result['mes']
        total_por_mes = result['total_por_mes']
        total = result['total']
        # print(bairro, mes, total_por_mes, total)
        for i in resultados_agrupados:
            # print(i)
            if i['bairro'] == bairro:
                i[mes]=total_por_mes
                i['total']=total
       
                
    #     else:
            # resultados_agrupados.append({'bairro': bairro, f'{mes}':  total_por_mes, 'total': total})   
    #       for item in resultados_agrupados:
    #           if item.bairro ==  bairro:
    #               item[result.mes]=result.total_por_mes


    # print(resultados_agrupados)
    context = {

os_ti/templates/nav_os.html
<div id="navegacao" class="container">
    <div class="row">
      <div class="col  d-flex">
        <a href="{% url 'os_ti:os_painel' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_painel" class="s-nav rounded-circle"></div>
            <p class="text-dark">Painel</p>
          </div>
        </a>  
        <a href="{% url 'os_ti:os_index' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_index" class="s-nav rounded-circle"></div>
            <p class="text-dark">Serviços</p>
          </div>
        </a>  
        <a href="{% url 'os_ti:add_os' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_solicitar" class="s-nav rounded-circle "></div>
            <p class="text-dark text-center">Solicitar</p>
          </div>
        </a>
        <a href="{% url 'ti_almoxarifado:index' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_almoxarifado" class="s-nav rounded-circle"></div>
            <p class="text-dark">Almoxarifado</p>
          </div>
        </a>              
        <a href="{% url 'os_ti:kpi' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_kpi" class="s-nav rounded-circle "></div>
            <p class="text-dark text-center">Indicadores</p>
          </div>
        </a>                     
        {% if request.user.is_staff %}
        <a href="{% url 'os_ti:funcionarios' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="os_funcionarios" class="s-nav rounded-circle"></div>
            <p class="text-dark">Funcionarios</p>
          </div>
        </a> 
        <!-- <a href="{% url 'administrativo' %}" class="me-3">
          <div class="d-flex flex-column align-items-center">
            <div id="admin" class="s-nav rounded-circle destaque"></div>
            <p class="text-dark">DJ-Admin</p>
          </div>
        </a> -->
        {% endif %}
      </div>
    </div>
  </div>
  <style>
    #os_inicio{      
      background-color: white !important;
      background-image: url(/static/images/icones/os_inicio.png);
      background-size: contain;
    }
    #os_solicitar{
      background-color: white !important;
      background-image: url(/static/images/icones/os_solicitar.png);
      background-size: contain;
    }
    #os_kpi{
      background-color: white !important;
      background-image: url(/static/images/icones/os_kpi.png);
      background-size: contain;
    }
    #os_almoxarifado{
      background-color: white !important;
      background-image: url(/static/images/icones/os_almoxarifado.png);
      background-size: contain;
    }
    #os_funcionarios{
      background-color: white !important;
      background-image: url(/static/images/icones/os_funcionarios.png);
      background-size: contain;
    }
    #os_painel{
      background-color: white !important;
      background-image: url(/static/images/icones/os_painel.png);
      background-size: contain;
    }
    #admin{
      background-color: white !important;
      background-image: url(/static/images/icones/bemestaranimal_admin.png);
      background-size: contain;
    }
  </style>

os_ti/templates/os_base.html
{% extends 'os_template.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block head_js %}
{% endblock %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main%}
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block end_js %}
{% endblock %}

os_ti/templates/os_header.html
{% load static %} 
{% load bootstrap5 %}
<header class="row">
  <link rel="stylesheet" href="static/css/header.css">
  <div class="col" style="border-bottom: 1px solid rgb(184, 184, 184);">
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">                                  
            <a class="navbar-brand" href="/">
              
              <img class="img-fluid logo" src="{% static '/images/logo.jpg' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item">                        
                  <a class=" header-items nav-link {%block index%}{%endblock%}" href="/">
                    Início
                  </a>
                </li>
                <li class="nav-item">                        
                  <a class="header-items nav-link{% block os %}{%endblock%}" href="{% url 'os_ti:add_os' %}">
                  Abrir Chamado
                  </a>
                </li>                     
                {% if request.user.is_staff %}
                <li class="nav-item">                                          
                  <div class="dropdown">
                    <button class="nav-link btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                      Administrativo
                    </button>
                    <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end text-start" aria-labelledby="dropdownMenuButton1">                      
                      {% comment %} <li>
                        <a class="dropdown-item py-2" href="{% url 'almoxarifado:index' %}">Almoxarifado</a>
                      </li>   {% endcomment %}
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'os_ti:funcionarios' %}">Funcionários</a>
                      </li> 
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'os_ti:os_index' %}">Ordem de Serviço</a>
                      </li>                                                                  
                    </ul>
                  </div>
                </li>
                {% endif %}               
              </ul>
              <div class="d-flex ms-auto">                                              
                {% if not request.user.is_authenticated %}
                <!-- <a href="/admin" class="btn text-uppercase" type="submit"><i class="fa-solid fa-user me-2"></i> Login</a> -->
                {% else %}
                <div class="dropdown">
                  <button class="btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user-large me-2"></i>
                    {{ request.user.first_name }}
                  </button>
                  <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                    {% if request.user.is_superuser %}
                    <li><a class="dropdown-item py-2 text-center" href="/admin/">Administração</a></li>
                    {% endif %}
                    <!-- <li><a class="dropdown-item py-2 text-center" href="#">Meu perfil</a></li> -->
                    <!-- <li><a class="dropdown-item py-2" href="#">Meu perfil</a></li> -->
                    <li>
                      <a class="dropdown-item text-center py-2" href="{% url 'os_ti:sairFunc' %}">
                        <i class="fa-solid fa-arrow-right-from-bracket me-2"></i></i> Logout                            
                      </a>
                    </li>
                  </ul>
                </div>
                
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
  </div>
</header>

os_ti/templates/os_header_login.html
{% load static %} 
{% load bootstrap5 %}
<header class="row">
  <link rel="stylesheet" href="static/css/header.css">
  <div class="col" style="border-bottom: 1px solid rgb(184, 184, 184);">
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">                                  
            <a class="navbar-brand" href="/">
              
              <img class="img-fluid logo" src="{% static '/images/logo.jpg' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <!-- <li class="nav-item">                        
                  <a class=" header-items nav-link {%block index%}{%endblock%}" href="/">
                    Início
                  </a>
                </li>
                <li class="nav-item">                        
                  <a class="header-items nav-link{% block os %}{%endblock%}" href="{% url 'os_ti:add_os' %}">
                  Abrir Chamado
                  </a>
                </li>                      -->
                {% if request.user.is_staff %}
                <li class="nav-item">                                          
                  <div class="dropdown">
                    <button class="nav-link btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                      Administrativo
                    </button>
                    <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end text-start" aria-labelledby="dropdownMenuButton1">                      
                      {% comment %} <li>
                        <a class="dropdown-item py-2" href="{% url 'almoxarifado:index' %}">Almoxarifado</a>
                      </li>   {% endcomment %}
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'os_ti:funcionarios' %}">Funcionários</a>
                      </li> 
                      <li>
                        <a class="dropdown-item py-2" href="{% url 'os_ti:os_index' %}">Ordem de Serviço</a>
                      </li>                                                                  
                    </ul>
                  </div>
                </li>
                {% endif %}               
              </ul>
              <div class="d-flex ms-auto">                                              
                {% if not request.user.is_authenticated %}
                <!-- <a href="/admin" class="btn text-uppercase" type="submit"><i class="fa-solid fa-user me-2"></i> Login</a> -->
                {% else %}
                <div class="dropdown">
                  <button class="btn" type="button" id="dropdownMenuPerfil" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user-large me-2"></i>
                    {{ request.user.first_name }}
                  </button>
                  <ul id="menu-perfil" class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                    {% if request.user.is_superuser %}
                    <li><a class="dropdown-item py-2 text-center" href="/admin/">Administração</a></li>
                    {% endif %}
                    <!-- <li><a class="dropdown-item py-2 text-center" href="#">Meu perfil</a></li> -->
                    <!-- <li><a class="dropdown-item py-2" href="#">Meu perfil</a></li> -->
                    <li>
                      <a class="dropdown-item text-center py-2" href="{% url 'os_ti:sairFunc' %}">
                        <i class="fa-solid fa-arrow-right-from-bracket me-2"></i></i> Logout                            
                      </a>
                    </li>
                  </ul>
                </div>
                
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
  </div>
</header>